# .github/workflows/generate_tally.yml

name: Generate Positivity Tally

on:
    pull_request:
        branches:
            - main
        paths:
            - DETECTION_RESULTS.tsv
            - positivity_tally.tsv
            - generate_tally.yml

jobs:
    generate-tally:
        name: Generate Positivity Tally
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install Dependencies
              run: |
                  pip install uv
                  uv venv
                  source .venv/bin/activate
                  uv pip install -r requirements.txt

            - name: Tally positive cartons per state
              run: |
                  source .venv/bin/activate
                  python3 scripts/positivity_tally.py \
                  DETECTION_RESULTS.tsv \
                  assets/positivity_tally.tsv

            - name: Commit positivity tally
              if: success()
              run: |
                  git config --global user.name 'GitHub Actions Bot'
                  git config --global user.email 'actions@github.com'
                  git add assets/positivity_tally.tsv
                  git fetch origin proposals
                  git commit -m "Updating positivity tally"
                  git push --force-with-lease origin HEAD:proposals
