# .github/workflows/validate.yml

name: Still Validation

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
            - proposals

jobs:
    build-and-test:
        name: Build and Test Go Application
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.20.x

            - name: Install Dependencies
              run: |
                  git clone https://github.com/danielecook/still.git

            - name: Build Go Application
              run: |
                  cd still
                  go build .
                  cd ..

            - name: Test Data Normalization
              run: |
                  ./still/still validate assets/still.schema DETECTION_RESULTS.tsv
              continue-on-error: true

            - name: Check Test Results
              if: ${{ steps.run-application-tests.outcome != 'success' }}
              run: |
                  echo "DETECTION_RESULTS.tsv tests failed. Pull request cannot be merged. Please double check the results from this GitHub workflow run to see which values must be corrected."
                  exit 1
